# Generated by Django 5.1.8 on 2025-04-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=6, unique=True)),
                ('full_name', models.CharField(max_length=320)),
                ('email', models.EmailField(max_length=320)),
                ('phone_number', models.CharField(blank=True, default='', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
